project: 
  type: website

website:
  title: "LiPaD"
  navbar:
    left:
      - href: contributors.qmd
        text: Contributors
      - href: https://lipad.ca/#about
        text: About
      - href: https://www.lipad.ca/blog/
        text: Blog
      - href: https://lipad.ca/contact/
        text: Contact

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false

editor: visual

site-url: .
home: contributors.qmd